### ISSUE TITLE
Documentation insufficient to try initial tests

### ISSUE THREAD

**Issue by FredsterCodeing** [elcajon-tech/addon-mosquitto-tailscale#14]
### The problem

Really like the idea of wrapping Tailscale and Mosquitto into one package. Removes the routing topic and there is nothing preventing another tailscale add on running for remote Home Assistant access. 
Want to test it and use it for site to site MQTT connection.

Need just a few pointers on how to config things. 

-Cant see how to configure tailscale for things like using exit routs on other nodes (as my first test I would connect Mosquitto to test.mosquitto.org so I would set up an exit node initially) 

-I'm guessing the Mosquitto.conf file goes in the same place as the official Mosquitto MQTT add on has it in /share/mosquitto/mosquitto.conf

### What version of Mosquitto & Tailscale has the issue?

0.1.3

### What was the last working version of Mosquitto & Tailscale?

0

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
-
```

### Anything in the logs that might be useful for us?

```txt
-
```

### Steps to reproduce the issue

-

### Additional information

-

**Comment by elcajon** [comment]
Hey @FredsterCodeing,

I removed most of the configuration options in this add on, as I just wanted a way to send data from an external Zigbee2mqtt instance to my MQTT broker without opening the appropriate ports over the network. 

> -Cant see how to configure tailscale for things like using exit routs on other nodes (as my first test I would connect Mosquitto to test.mosquitto.org so I would set up an exit node initially)

Can you elaborate on what exactly you want to achieve? If you want to connect to test.mosquitto.org, do you want to use the official test broker? That would have nothing to do with the broker included in the add-on at this point?
The broker in the add-on does not actually need any tailscale routes, since from the add-on's point of view only incoming connections are relevant. If you see a relevant usecase there please let me know and I will add the option.

> -I'm guessing the Mosquitto.conf file goes in the same place as the official Mosquitto MQTT add on has it in /share/mosquitto/mosquitto.conf

I had removed the functionality of the official Home Assistant add-on here because I had no use for it, but I'm happy to add it back if needed.

**Comment by FredsterCodeing** [comment]
Hey Elcajo, 
Thanks for the reply. I’m trying to set up two home assistant os instances. One in a remote location with very poor internet access. I want to be able to monitor and control a few sensors and switches at this remote site. I intend to use MQTT as the communication system between the sites. I also like the Tailscale tool and what it can enable without being a full network engineer. As yet though the Tailscale add-ons I have tried are just allowing me to get onto home assistant remotely. I have not found a way to allow the home assistant os environment or add-ons to connect out over the Tailscale VPN. 
When I found your solution here a bell rang. Site to site connections built into the docker with MQTT sounds nice. 

test.mosquitto.org is a testing idea. Testing one install against test.mosquitto.org would just let me know I got something right before adding a second site.  
I also might like to attach MQTT Explorer (the community add-on) as part of testing and any troubleshooting. 
I guess these steps may not be necessary. 
Possibly if the tailscale interface was available outside the docker container in the Tailscale community Add-on then it could be used by Mosquitto MQTT. I am not informed enough to really call out the complications.

**Comment by elcajon** [comment]
I integrate the functionality of the official add-on regarding customizing and did some testing. The whole thing turns out surprisingly simple. I added a FAQ section in the documentation with the configuration I used. 
For me, the result was that my Zigbee2MQTT entities from my main HA instance were all available together in my test instance. (Should also work vice versa) 
Feel free to try if the changes work for you, after upgrading to the current version of the add on which is v0.2.0.
